CREATE TABLE t_random 
(id SERIAL PRIMARY KEY, 
created timestamp without time zone, 
name  VARCHAR(100) NOT NULL default ('[0:3]={Akbar,Ashwin,Faruk,Sahul}'::text[])[floor(random()*4)], 
p1 numeric default round(random()*5),
p2 numeric default round(random()*10),
p3 numeric default round(random()*100),
p4 numeric default round(random()*1000),
p5 numeric default round(random()*10000),
p6 numeric default round(random()*100000),
p7 numeric default round(random()*42),
p8 numeric default round(random()*27),
p9 numeric default round(random()*2),
p10 numeric default round(random()*3),
p11 numeric default round(random()*5),
p12 numeric default round(random()*7),
p13 numeric default round(random()*11),
p14 numeric default round(random()*13),
p15 numeric default round(random()*17),
p16 numeric default round(random()*19),
p17 numeric default round(random()*23),
p18 numeric default round(random()*29),
p19 numeric default round(random()*31),
p20 numeric default round(random()*37),
p21 numeric default round(random()*41),
p22 numeric default round(random()*42),
p23 numeric default round(random()*47)
);
